# source:  https://inara.cz/starfield/resources/
# 166 unique base-game crafting resources
#   47 inorganic
#   34 manufactured
#   31 organic
resource_id_map = {
    1: 'Adaptive Frame',
    2: 'Adhesive',
    3: 'Aldumite',
    4: 'Aldumite Drilling Rig',
    5: 'Alkanes',
    6: 'Aluminum',
    7: 'Amino Acids',
    8: 'Analgesic',
    9: 'Antimicrobial',
    10: 'Antimony',
    11: 'Aqueous Hematite',
    12: 'Argon',
    13: 'Aromatic',
    14: 'Austenitic Manifold',
    15: 'Benzene',
    16: 'Beryllium',
    17: 'Biosuppressant',
    18: 'Caelumite',
    19: 'Caesium',
    20: 'Carboxylic Acids',
    21: 'Charged Diodes',
    22: 'Chlorine',
    23: 'Chlorosilanes',
    24: 'Cobalt',
    25: 'Comm Relay',
    26: 'Control Rod',
    27: 'Copper',
    28: 'Cosmetic',
    29: 'Drilling Rig',
    30: 'Dysprosium',
    31: 'Europium',
    32: 'Fiber',
    33: 'Fluorine',
    34: 'Gastronomic Delight',
    35: 'Gold',
    36: 'Hallucinogen',
    37: 'Helium-3',
    38: 'High-Tensile Spidroin',
    39: 'Hypercatalyst',
    40: 'Immunostimulant',
    41: 'Indicite',
    42: 'Indicite Wafer',
    43: 'Ionic Liquids',
    44: 'Iridium',
    45: 'Iron',
    46: 'Isocentered Magnet',
    47: 'Isotopic Coolant',
    48: 'Large Round Primer',
    49: 'Lead',
    50: 'Lithium',
    51: 'Lubricant',
    52: 'Luxury Textile',
    53: 'Mag Pressure Tank',
    54: 'Magnetic Diodes',
    55: 'Membrane',
    56: 'Memory Substrate',
    57: 'Mercury',
    58: 'Metabolic Agent',
    59: 'Microsecond Regulator',
    60: 'Molecular Sieve',
    61: 'Monopropellant',
    62: 'Neodymium',
    63: 'Neon',
    64: 'Neurologic',
    65: 'Nickel',
    66: 'Nuclear Fuel Rod',
    67: 'Nutrient',
    68: 'Ornamental Material',
    69: 'Palladium',
    70: 'Paramagnon Conductor',
    71: 'Pigment',
    72: 'Platinum',
    73: 'Plutonium',
    74: 'Polymer',
    75: 'Polytextile',
    76: 'Positron Battery',
    77: 'Power Circuit',
    78: 'Quark-Degenerate Tissues',
    79: 'Reactive Gauge',
    80: 'Rothicite',
    81: 'Rothicite Magnet',
    82: 'Sealant',
    83: 'Sedative',
    84: 'Semimetal Wafer',
    85: 'Silver',
    86: 'Small Round Primer',
    87: 'Solvent',
    88: 'Spice',
    89: 'Sterile Nanotubes',
    90: 'Stimulant',
    91: 'Structural Material',
    92: 'Substrate Molecule Sieve',
    93: 'Supercooled Magnet',
    94: 'Tantalum',
    95: 'Tasine',
    96: 'Tasine Superconductor',
    97: 'Tau Grade Rheostat',
    98: 'Tetrafluorides',
    99: 'Titanium',
    100: 'Toxin',
    101: 'Tungsten',
    102: 'Uranium',
    103: 'Vanadium',
    104: 'Veryl',
    105: 'Veryl-Treated Manifold',
    106: 'Vytinium',
    107: 'Vytinium Fuel Rod',
    108: 'Water',
    109: 'Xenon',
    110: 'Ytterbium',
    111: 'Zero Wire',
    112: 'Zero-G Gimbal',
}


# source: https://inara.cz/starfield/outpost-modules/
# 387 unique base-game outpost module recipes
outpost_module_id_map = {
    1: 'Animal Hide Rug',
    2: 'Animal Husbandry Facility',
    3: 'Animal Husbandry Facility - Commercial',
    4: 'Animal Husbandry Facility - Industrial',
    5: 'Backpack Stand',
    6: 'Ballistic Turret Mk I',
    7: 'Ballistic Turret Mk II',
    8: 'Ballistic Turret Mk III',
    9: 'Bar Table',
    10: 'Bed (Starborn)',
    11: 'Bed 1',
    12: 'Bed 2',
    13: 'Bed 3',
    14: 'Bench 1',
    15: 'Bench 2',
    16: 'Bench 3',
    17: 'Bench 4',
    18: 'Bench 5',
    19: 'Bench 6',
    20: 'Bookcase',
    21: 'Bounty Poster',
    22: 'Bunk Bed',
    23: 'Bunk Bed (variant)',
    24: 'Cabinets',
    25: 'Cargo Link',
    26: 'Cargo Link - Inter-System',
    27: 'Carts',
    28: 'Chair 1',
    29: 'Chair 10',
    30: 'Chair 11',
    31: 'Chair 12',
    32: 'Chair 13',
    33: 'Chair 14',
    34: 'Chair 15',
    35: 'Chair 16',
    36: 'Chair 2',
    37: 'Chair 3',
    38: 'Chair 4',
    39: 'Chair 5',
    40: 'Chair 6',
    41: 'Chair 7',
    42: 'Chair 8',
    43: 'Chair 9',
    44: 'Cleaning',
    45: 'Coffee Maker',
    46: 'Coffee Table',
    47: 'Coffee Table (variant)',
    48: 'Compound Fabricator',
    49: 'Conference Table',
    50: 'Console Desks',
    51: 'Constellation Mission Board',
    52: 'Containers (large)',
    53: 'Containers (safe)',
    54: 'Containers (small)',
    55: 'Cooking Station',
    56: 'Couch 1',
    57: 'Couch 2',
    58: 'Couch 3',
    59: 'Couch 4',
    60: 'Couches',
    61: 'Crew Station',
    62: 'Dart boards',
    63: 'Data Slate Display',
    64: 'Data Slate Display (variant)',
    65: 'Desk',
    66: 'Desk (variant)',
    67: 'Desk Monitor',
    68: 'Desks',
    69: 'Diagnostic Machine',
    70: 'Display Case',
    71: 'Display Shelf',
    72: 'Display Shelf (variant)',
    73: 'Drink Machine',
    74: 'Earth Globe',
    75: 'End Table',
    76: 'End Table (variant)',
    77: 'Engineering Robot',
    78: 'Extractor - Aldumite',
    79: 'Extractor - Aldumite - Commercial',
    80: 'Extractor - Aldumite - Industrial',
    81: 'Extractor - Alkanes',
    82: 'Extractor - Alkanes - Commercial',
    83: 'Extractor - Alkanes - Industrial',
    84: 'Extractor - Alkanes Vapor',
    85: 'Extractor - Alkanes Vapor - Commercial',
    86: 'Extractor - Alkanes Vapor - Industrial',
    87: 'Extractor - Aluminum',
    88: 'Extractor - Aluminum - Commercial',
    89: 'Extractor - Aluminum - Industrial',
    90: 'Extractor - Antimony',
    91: 'Extractor - Antimony - Commercial',
    92: 'Extractor - Antimony - Industrial',
    93: 'Extractor - Argon',
    94: 'Extractor - Argon - Commercial',
    95: 'Extractor - Argon - Industrial',
    96: 'Extractor - Benzene',
    97: 'Extractor - Benzene - Commercial',
    98: 'Extractor - Benzene - Industrial',
    99: 'Extractor - Benzene Vapor',
    100: 'Extractor - Benzene Vapor - Commercial',
    101: 'Extractor - Benzene Vapor - Industrial',
    102: 'Extractor - Beryllium',
    103: 'Extractor - Beryllium - Commercial',
    104: 'Extractor - Beryllium - Industrial',
    105: 'Extractor - Caesium',
    106: 'Extractor - Caesium - Commercial',
    107: 'Extractor - Caesium - Industrial',
    108: 'Extractor - Carboxylic Acids',
    109: 'Extractor - Carboxylic Acids - Commercial',
    110: 'Extractor - Carboxylic Acids - Industrial',
    111: 'Extractor - Chlorine',
    112: 'Extractor - Chlorine - Commercial',
    113: 'Extractor - Chlorine - Industrial',
    114: 'Extractor - Chlorine Vapor',
    115: 'Extractor - Chlorine Vapor - Commercial',
    116: 'Extractor - Chlorine Vapor - Industrial',
    117: 'Extractor - Chlorosilanes',
    118: 'Extractor - Chlorosilanes - Commercial',
    119: 'Extractor - Chlorosilanes - Industrial',
    120: 'Extractor - Cobalt',
    121: 'Extractor - Cobalt - Commercial',
    122: 'Extractor - Cobalt - Industrial',
    123: 'Extractor - Copper',
    124: 'Extractor - Copper - Commercial',
    125: 'Extractor - Copper - Industrial',
    126: 'Extractor - Dysprosium',
    127: 'Extractor - Dysprosium - Commercial',
    128: 'Extractor - Dysprosium - Industrial',
    129: 'Extractor - Europium',
    130: 'Extractor - Europium - Commercial',
    131: 'Extractor - Europium - Industrial',
    132: 'Extractor - Fluorine',
    133: 'Extractor - Fluorine - Commercial',
    134: 'Extractor - Fluorine - Industrial',
    135: 'Extractor - Fluorine Vapor',
    136: 'Extractor - Fluorine Vapor - Commercial',
    137: 'Extractor - Fluorine Vapor - Industrial',
    138: 'Extractor - Gold',
    139: 'Extractor - Gold - Commercial',
    140: 'Extractor - Gold - Industrial',
    141: 'Extractor - Helium-3',
    142: 'Extractor - Helium-3 - Commercial',
    143: 'Extractor - Helium-3 - Industrial',
    144: 'Extractor - Helium-3 Vapor',
    145: 'Extractor - Helium-3 Vapor - Commercial',
    146: 'Extractor - Helium-3 Vapor - Industrial',
    147: 'Extractor - Indicite',
    148: 'Extractor - Indicite - Commercial',
    149: 'Extractor - Indicite - Industrial',
    150: 'Extractor - Ionic Liquids',
    151: 'Extractor - Ionic Liquids - Commercial',
    152: 'Extractor - Ionic Liquids - Industrial',
    153: 'Extractor - Iridium',
    154: 'Extractor - Iridium - Commercial',
    155: 'Extractor - Iridium - Industrial',
    156: 'Extractor - Iron',
    157: 'Extractor - Iron - Commercial',
    158: 'Extractor - Iron - Industrial',
    159: 'Extractor - Lead',
    160: 'Extractor - Lead - Commercial',
    161: 'Extractor - Lead - Industrial',
    162: 'Extractor - Lithium',
    163: 'Extractor - Lithium - Commercial',
    164: 'Extractor - Lithium - Industrial',
    165: 'Extractor - Mercury',
    166: 'Extractor - Mercury - Commercial',
    167: 'Extractor - Mercury - Industrial',
    168: 'Extractor - Neodymium',
    169: 'Extractor - Neodymium - Commercial',
    170: 'Extractor - Neodymium - Industrial',
    171: 'Extractor - Neon',
    172: 'Extractor - Neon - Commercial',
    173: 'Extractor - Neon - Industrial',
    174: 'Extractor - Nickel',
    175: 'Extractor - Nickel - Commercial',
    176: 'Extractor - Nickel - Industrial',
    177: 'Extractor - Palladium',
    178: 'Extractor - Palladium - Commercial',
    179: 'Extractor - Palladium - Industrial',
    180: 'Extractor - Platinum',
    181: 'Extractor - Platinum - Commercial',
    182: 'Extractor - Platinum - Industrial',
    183: 'Extractor - Plutonium',
    184: 'Extractor - Plutonium - Commercial',
    185: 'Extractor - Plutonium - Industrial',
    186: 'Extractor - Rothicite',
    187: 'Extractor - Rothicite - Commercial',
    188: 'Extractor - Rothicite - Industrial',
    189: 'Extractor - Silver',
    190: 'Extractor - Silver - Commercial',
    191: 'Extractor - Silver - Industrial',
    192: 'Extractor - Tantalum',
    193: 'Extractor - Tantalum - Commercial',
    194: 'Extractor - Tantalum - Industrial',
    195: 'Extractor - Tasine',
    196: 'Extractor - Tasine - Commercial',
    197: 'Extractor - Tasine - Industrial',
    198: 'Extractor - Tetrafluorides',
    199: 'Extractor - Tetrafluorides - Commercial',
    200: 'Extractor - Tetrafluorides - Industrial',
    201: 'Extractor - Titanium',
    202: 'Extractor - Titanium - Commercial',
    203: 'Extractor - Titanium - Industrial',
    204: 'Extractor - Tungsten',
    205: 'Extractor - Tungsten - Commercial',
    206: 'Extractor - Tungsten - Industrial',
    207: 'Extractor - Uranium',
    208: 'Extractor - Uranium - Commercial',
    209: 'Extractor - Uranium - Industrial',
    210: 'Extractor - Vanadium',
    211: 'Extractor - Vanadium - Commercial',
    212: 'Extractor - Vanadium - Industrial',
    213: 'Extractor - Veryl',
    214: 'Extractor - Veryl - Commercial',
    215: 'Extractor - Veryl - Industrial',
    216: 'Extractor - Vytinium',
    217: 'Extractor - Vytinium - Commercial',
    218: 'Extractor - Vytinium - Industrial',
    219: 'Extractor - Water',
    220: 'Extractor - Water - Commercial',
    221: 'Extractor - Water - Industrial',
    222: 'Extractor - Water Vapor',
    223: 'Extractor - Water Vapor - Commercial',
    224: 'Extractor - Water Vapor - Industrial',
    225: 'Extractor - Xenon',
    226: 'Extractor - Xenon - Commercial',
    227: 'Extractor - Xenon - Industrial',
    228: 'Extractor - Ytterbium',
    229: 'Extractor - Ytterbium - Commercial',
    230: 'Extractor - Ytterbium - Industrial',
    231: 'Fancy Bookcase',
    232: 'Fancy Sofa',
    233: 'Flood Lamps',
    234: 'Floor Mats',
    235: 'Four Wall Hab',
    236: 'Four Wall Hab - Double',
    237: 'Fueled Generator',
    238: 'Garden Mini Bot',
    239: 'Greenhouse',
    240: 'Greenhouse - Commercial',
    241: 'Greenhouse - Industrial',
    242: 'Hab Round',
    243: 'Hallway - Hydroponic',
    244: 'Hallway - Industrial',
    245: 'Hallway - Military',
    246: 'Hallway - Science',
    247: 'Hand Carts',
    248: 'Hanging Plants',
    249: 'Hanging Rug',
    250: 'Helmet Case',
    251: 'Hydroponic Hab A',
    252: 'Hydroponic Hab B',
    253: 'Hydroponic Hab Round',
    254: 'Industrial Light Post',
    255: 'Industrial Wall Light',
    256: 'Industrial Wall Lights',
    257: 'Industrial Workbench',
    258: 'Landing Pad - Small',
    259: 'Landing Pad with Shipbuilder',
    260: 'Large Hex Hab',
    261: 'Laser Turret Mk I',
    262: 'Laser Turret Mk II',
    263: 'Laser Turret Mk III',
    264: 'Light Post',
    265: 'Light Posts',
    266: 'Light Posts (variant)',
    267: 'Logistics Robot',
    268: 'Long Oval Table',
    269: 'Long Table',
    270: 'Mannequins',
    271: 'Mannequins (variant 1)',
    272: 'Mannequins (variant 2)',
    273: 'Mannequins (variant 3)',
    274: 'Metal Sculpture',
    275: 'Military Hab',
    276: 'Mission Board',
    277: 'Model Ship (starship)',
    278: 'Model Ship (wooden)',
    279: 'Mounted Ashta',
    280: 'Mounted Beetle Crab',
    281: 'Mounted Lock Jaw',
    282: 'Mounted Radar Face',
    283: 'Mounted Red Mile Apex',
    284: 'Mounted Sea Bat',
    285: 'Multiplex Fabricator',
    286: 'Navigation Consoles',
    287: 'ObservatoryFree Creation',
    288: 'Old Computer',
    289: 'Orrery Table',
    290: 'Outpost Airlock',
    291: 'Outpost Beacon',
    292: 'Oval Rug',
    293: 'Pedestals',
    294: 'Pedestals (empty)',
    295: 'Pharmaceutical Lab',
    296: 'Picture Frame',
    297: 'Plant Shelf',
    298: 'Planters',
    299: 'Portable Stove Top',
    300: 'Posters',
    301: 'Posters (variant 1)',
    302: 'Posters (variant 2)',
    303: 'Potted Plants',
    304: 'Power Management Robot',
    305: 'Powered Switch',
    306: 'Punching Bag',
    307: 'Reactor',
    308: 'Reactor - Advanced',
    309: 'Rectangle Rug',
    310: 'Refrigerator',
    311: 'Research Lab',
    312: 'Room Dividers',
    313: 'Round Rug',
    314: 'Rug',
    315: 'Rug (variant)',
    316: 'Sanitation Mini Bot',
    317: 'Scan Booster',
    318: 'Scan Booster - Advanced',
    319: 'Scan Booster - Military Grade',
    320: 'Science Hab Flat Small',
    321: 'Science Hab Small',
    322: 'Sculpture',
    323: 'Security Mini Bot',
    324: 'Security Robot',
    325: 'Security Robot (armored)',
    326: 'Self-Service Bounty Clearance',
    327: 'Shelf',
    328: 'Shelf (variant)',
    329: 'Side Table',
    330: 'Side Table (variant)',
    331: 'Signs',
    332: 'Simple Fabricator',
    333: 'Sink',
    334: 'Sleeping Bags',
    335: 'Small Hex Hab',
    336: 'Solar Array',
    337: 'Solar Dome',
    338: 'Space Frog Posters',
    339: 'Spacesuit Workbench',
    340: 'Standing Mirror',
    341: 'Statues',
    342: 'Stool 1',
    343: 'Stool 2',
    344: 'Stool 3',
    345: 'Stool 4',
    346: 'Stool 5',
    347: 'Storage - Gas',
    348: 'Storage - Gas - Large',
    349: 'Storage - Gas - Medium',
    350: 'Storage - Liquid',
    351: 'Storage - Liquid - Large',
    352: 'Storage - Liquid - Medium',
    353: 'Storage - Solid',
    354: 'Storage - Solid - Large',
    355: 'Storage - Solid - Medium',
    356: 'Storage Bins',
    357: 'Surgical Bed',
    358: 'Surgical Bed (variant)',
    359: 'Table 1',
    360: 'Table 2',
    361: 'Table 3',
    362: 'Tables',
    363: 'Tick Turret Mk I',
    364: 'Toilet',
    365: 'Toilet Paper',
    366: 'Towel Rack',
    367: 'Transfer Container',
    368: 'Trash Cans',
    369: 'Wall Cabinets',
    370: 'Wall Monitor',
    371: 'Wall Shelf',
    372: 'Warehouse - Large',
    373: 'Warehouse - Medium',
    374: 'Warehouse - Small',
    375: 'Watchtower',
    376: 'Water Cooler',
    377: 'Weapon Case',
    378: 'Weapon Display Case',
    379: 'Weapon Rack',
    380: 'Weapon Rack (variant)',
    381: 'Weapon Rack (wall)',
    382: 'Weapon Workbench',
    383: 'Weight Bench',
    384: 'White Board - Floor',
    385: 'Wind Turbine',
    386: 'Wind Turbine - Advanced',
    387: 'Wooden Desk',
}

# 421 unique base-game crafting recipes
#   (387 outpost modules, 34 manufactured resources)


name_map = {'name': 'name', 'requiredAldumite': 'requiredAldumite', 'requiredAlkanes': 'requiredAlkanes', 'requiredAluminum': 'requiredAluminum', 'requiredAntimony': 'requiredAntimony', 'requiredAqueousHematite': 'requiredAqueousHematite', 'requiredArgon': 'requiredArgon', 'requiredBenzene': 'requiredBenzene', 'requiredBeryllium': 'requiredBeryllium', 'requiredCaelumite': 'requiredCaelumite', 'requiredCaesium': 'requiredCaesium', 'requiredCarboxylicAcids': 'requiredCarboxylicAcids', 'requiredChlorine': 'requiredChlorine', 'requiredChlorosilanes': 'requiredChlorosilanes', 'requiredCobalt': 'requiredCobalt', 'requiredCopper': 'requiredCopper', 'requiredDysprosium': 'requiredDysprosium', 'requiredEuropium': 'requiredEuropium', 'requiredFlourine': 'requiredFlourine', 'requiredGold': 'requiredGold', 'requiredHelium3': 'requiredHelium3', 'requiredIndicite': 'requiredIndicite', 'requiredIonicLiquids': 'requiredIonicLiquids', 'requiredIridium': 'requiredIridium', 'requiredIron': 'requiredIron', 'requiredLead': 'requiredLead', 'requiredLithium': 'requiredLithium', 'requiredMercury': 'requiredMercury', 'requiredNeodymium': 'requiredNeodymium', 'requiredNeon': 'requiredNeon', 'requiredNickel': 'requiredNickel', 'requiredPalladium': 'requiredPalladium', 'requiredPlatinum': 'requiredPlatinum', 'requiredPlutonium': 'requiredPlutonium', 'requiredRothicite': 'requiredRothicite', 'requiredSilver': 'requiredSilver', 'requiredTantalum': 'requiredTantalum', 'requiredTasine': 'requiredTasine', 'requiredTetraflourides': 'requiredTetraflourides', 'requiredTitanium': 'requiredTitanium', 'requiredTungsten': 'requiredTungsten', 'requiredUranium': 'requiredUranium', 'requiredVanadium': 'requiredVanadium', 'requiredVeryl': 'requiredVeryl', 'requiredVytinium': 'requiredVytinium', 'requiredWater': 'requiredWater', 'requiredXenon': 'requiredXenon', 'requiredYtterbium': 'requiredYtterbium', 'requiredAdhesive': 'requiredAdhesive', 'requiredAminoAcids': 'requiredAminoAcids', 'requiredAnalgesic': 'requiredAnalgesic', 'requiredAntimicrobial': 'requiredAntimicrobial', 'requiredAromatic': 'requiredAromatic', 'requiredBiosuppressant': 'requiredBiosuppressant', 'requiredCosmetic': 'requiredCosmetic', 'requiredFiber': 'requiredFiber', 'requiredGastronoicDelight': 'requiredGastronoicDelight', 'requiredHallucinogen': 'requiredHallucinogen', 'requiredHighTensileSpidroin': 'requiredHighTensileSpidroin', 'requiredHypercatalyst': 'requiredHypercatalyst', 'requiredImmunostimulant': 'requiredImmunostimulant', 'requiredLubricant': 'requiredLubricant', 'requiredLuxuryTextile': 'requiredLuxuryTextile', 'requiredMembrane': 'requiredMembrane', 'requiredMemorySubstrate': 'requiredMemorySubstrate', 'requiredMetabolicAgent': 'requiredMetabolicAgent', 'requiredNeurologic': 'requiredNeurologic', 'requiredNutrient': 'requiredNutrient', 'requiredOrnamentalMaterial': 'requiredOrnamentalMaterial', 'requiredPigment': 'requiredPigment', 'requiredPolymer': 'requiredPolymer', 'requiredQuarkDegenerateTissues': 'requiredQuarkDegenerateTissues', 'requiredSealant': 'requiredSealant', 'requiredSedative': 'requiredSedative', 'requiredSolvent': 'requiredSolvent', 'requiredSpice': 'requiredSpice', 'requiredStimulant': 'requiredStimulant', 'requiredStructuralMaterials': 'requiredStructuralMaterials', 'requiredToxin': 'requiredToxin', 'requiredAdaptiveFrame': 'requiredAdaptiveFrame', 'requiredAldumiteDrillingRig': 'requiredAldumiteDrillingRig', 'requiredAusteniticManifold': 'requiredAusteniticManifold', 'requiredCommRelay': 'requiredCommRelay', 'requiredControlRod': 'requiredControlRod', 'requiredDrillingRig': 'requiredDrillingRig', 'requiredIndiciteWafer': 'requiredIndiciteWafer', 'requiredIsocenteredMagnet': 'requiredIsocenteredMagnet', 'requiredIsotopicCoolant': 'requiredIsotopicCoolant', 'requiredMagPressureTank': 'requiredMagPressureTank', 'requiredMicrosecondRegulator': 'requiredMicrosecondRegulator', 'requiredMolecularSieve': 'requiredMolecularSieve', 'requiredMonopropellant': 'requiredMonopropellant', 'requiredNuclearFuelRod': 'requiredNuclearFuelRod', 'requiredParamagnonConductor': 'requiredParamagnonConductor', 'requiredPolytextile': 'requiredPolytextile', 'requiredPositronBattery': 'requiredPositronBattery', 'requiredPowerCircuit': 'requiredPowerCircuit', 'requiredReactiveGauge': 'requiredReactiveGauge', 'requiredRothiciteMagnet': 'requiredRothiciteMagnet', 'requiredSemimetalWafer': 'requiredSemimetalWafer', 'requiredSterileNanotubes': 'requiredSterileNanotubes', 'requiredSubstrateMoleculeSieve': 'requiredSubstrateMoleculeSieve', 'requiredSupercooledMagnet': 'requiredSupercooledMagnet', 'requiredTasineSuperconductor': 'requiredTasineSuperconductor', 'requiredTauGradeRheostat': 'requiredTauGradeRheostat', 'requiredVerylTreatedManifold': 'requiredVerylTreatedManifold', 'requiredVytiniumFuelRod': 'requiredVytiniumFuelRod', 'requiredZeroWire': 'requiredZeroWire', 'requiredZeroGGimbal': 'requiredZeroGGimbal'}
