from django.db import connection, models


# 385 unique base-game outpost module recipes
class OutpostModule(models.Model):
    objects = models.Manager()
    module_id = models.SmallIntegerField(primary_key=True, unique=True, null=False)
    name = models.CharField(max_length=50, unique=True, null=False)
    category = models.CharField(max_length=50, unique=False, null=False)
    power = models.SmallIntegerField(null=False, unique=False)
    recipe_id = models.SmallIntegerField(null=False, unique=True)


# 471 unique base-game crafting recipes
#   (385 outpost modules, 88 manufactured resources)
class Recipe(models.Model):
    objects = models.Manager()
    recipe_id = models.SmallIntegerField(primary_key=True, unique=True, null=False)
    description = models.CharField(max_length=10, null=True, blank=True, default=None)
    required_Aldumite = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Alkanes = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Aluminum = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Antimony = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Aqueous_Hematite = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Argon = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Benzene = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Beryllium = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Caelumite = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Caesium = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Carboxylic_Acids = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Chlorine = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Chlorosilanes = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Cobalt = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Copper = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Dysprosium = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Europium = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Flourine = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Gold = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Helium_3 = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Indicite = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Ionic_Liquids = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Iridium = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Iron = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Lead = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Lithium = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Mercury = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Neodymium = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Neon = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Nickel = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Palladium = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Platinum = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Plutonium = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Rothicite = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Silver = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Tantalum = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Tasine = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Tetraflourides = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Titanium = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Tungsten = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Uranium = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Vanadium = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Veryl = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Vytinium = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Water = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Xenon = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Ytterbium = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Adhesive = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Amino_Acids = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Analgesic = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Antimicrobial = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Aromatic = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Biosuppressant = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Cosmetic = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Fiber = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Gastronoic_Delight = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Hallucinogen = models.SmallIntegerField(null=True, blank=True, default=None)
    required_High_Tensile_Spidroin = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Hypercatalyst = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Immunostimulant = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Lubricant = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Luxury_Textile = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Membrane = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Memory_Substrate = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Metabolic_Agent = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Neurologic = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Nutrient = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Ornamental_Material = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Pigment = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Polymer = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Quark_Degenerate_Tissues = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Sealant = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Sedative = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Solvent = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Spice = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Stimulant = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Structural_Materials = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Toxin = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Adaptive_Frame = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Aldumite_Drilling_Rig = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Austenitic_Manifold = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Comm_Relay = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Control_Rod = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Drilling_Rig = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Indicite_Wafer = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Isocentered_Magnet = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Isotopic_Coolant = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Mag_Pressure_Tank = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Microsecond_Regulator = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Molecular_Sieve = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Monopropellant = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Nuclear_Fuel_Rod = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Paramagnon_Conductor = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Polytextile = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Positron_Battery = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Power_Circuit = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Reactive_Gauge = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Rothicite_Magnet = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Semimetal_Wafer = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Sterile_Nanotubes = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Substrate_Molecule_Sieve = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Supercooled_Magnet = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Tasine_Superconductor = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Tau_Grade_Rheostat = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Veryl_Treated_Manifold = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Vytinium_Fuel_Rod = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Zero_Wire = models.SmallIntegerField(null=True, blank=True, default=None)
    required_Zero_G_Gimbal = models.SmallIntegerField(null=True, blank=True, default=None)


# 88 unique base-game crafting resources
class Resource(models.Model):
    objects = models.Manager()
    resource_id = models.SmallIntegerField(primary_key=True, unique=True, null=False)
    name = models.CharField(max_length=10, unique=True, null=False)
    inorganic = models.BooleanField(unique=False, null=False)
    manufactured = models.BooleanField(unique=False, null=False)
    organic = models.BooleanField(unique=False, null=False)
    recipe_id = models.SmallIntegerField(unique=False, null=True, blank=True, default=None)
